### ISSUE TITLE
Allow per-user timezone configuration

### ISSUE THREAD

**Issue by theastropath** [theastropath/turbot#12]
I think we need to make it so that users can configure their timezone in order to make some logic about morning/afternoon prices easier to work with, since we have users across multiple timezones sharing info.

I think there should be a new command that would allow users to configure their own timezone. 
 Preferably this would be specified using something like the names from the tz database for formatted ones such as America/Toronto or America/Los_Angeles.  Using these names means we wouldn't need to think about DST (and whether it applies) as I believe there are libraries to handle conversions from those names to the appropriate timezones.

If a user has a timezone configured, we would display all their logged information using their local timezone:
 * !history would all be their timezone
 * !bestsell would be a mix of timezones per person which would make it easier for people to see if the price is still valid or not (Ie. if it was before or after noon)
 * Graph would show the local timezone for the X-axis

Some commands could also be updated to use the new timezone information.  For example, !bestsell and !bestbuy could know to not show the prices if logged in the morning and it is now the afternoon in the loggers timezone

**Comment by lexicalunit** [comment]
This could be done using the users preference file added in https://github.com/theastropath/turbot/pull/44.

**Comment by theastropath** [comment]
Agreed, that makes the most sense.  I had been thinking about where that information was going to be stored anyway.  Problem solved!

**Comment by lexicalunit** [comment]
https://github.com/theastropath/turbot/pull/50 adds the user preference and updates just the `!predict` command to work right if the user has set it. I haven't yet gone through all the other code to make sure it uses it as well, but that's what would be required to close this issue I think. Still, progress!

**Comment by lexicalunit** [comment]
While there are certainly improvements that could be made to the bestsell command, I think with the addition of timezone awareness to buy, sell, fish, bug, history, and predict commands that we can close out this ticket. Those commands are all now aware of a user's timezone in the proper way. I don't think it makes sense to add timezone awareness to any of the other commands. Maaaaaaybe a cause could be made for the !graph command when it's making a graph for a single user but that kind of improvement could be captured by #16.

**Comment by theastropath** [comment]
Agreed.  Closing this now.
