### ISSUE TITLE
Support multiple servers

### ISSUE THREAD

**Issue by lexicalunit** [theastropath/turbot#124]
This may actually work fine as the code is now, but it's never been tested.

**Comment by theastropath** [comment]
It sort of works (I had our instance in the main server and my own at the same time), but some things don't like it if they can't find a user as a member of the server.  We would just need to add logic to ignore data for users not on the same server.

**Comment by lexicalunit** [comment]
One issue that might arise is resource contention. Like for the tmp files like `tmp/graphcmd.png` for example. Maybe those could be created on a per-service basis like `tmp/{server}-graphcmd.png` 🤷‍♀️

**Comment by lexicalunit** [comment]
So I've been testing things on multiple servers since https://github.com/theastropath/turbot/pull/173 and it seems like it pretty much works just fine.

The only issue that I can see is that anyone on any server that is a Turbot Admin will have the power to call `!reset` and when they do it will affect all users on all servers.

Perhaps we just need to make it so `!reset` only resets prices of users that are found on the server where they command was run.
