### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by lexicalunit** [theastropath/turbot#19]
So that everyone can't just run the clear and reset commands.

**Comment by theastropath** [comment]
Just to jot down an idea I had on the subject of permissions, I thought it would be good if Turbot checked actual Discord roles to assign permissions.  Ideally the server admin may be able to use a command that defines what role specifically is the "Turbot Admin" role, or perhaps that could be configured on the Turbot side.

The server admin could assign the Turbot Admin role to the person who should be in charge of it.

**Comment by lexicalunit** [comment]
We could also have this be a column in the users data introduced in https://github.com/theastropath/turbot/pull/44 if we wanted. Though having a role is probably more secure and versatile. It doesn't require that someone edit a file and restart the server to add someone to the list of authorized users.

**Comment by theastropath** [comment]
It might make sense to support both, just in case.
