### ISSUE TITLE
Art command

### ISSUE THREAD

**Issue by lexicalunit** [theastropath/turbot#57]

**Comment by theastropath** [comment]
In addition to basic info regarding if you have it or not and searching to see who has what, I think Turbot should be able to provide a brief description of the difference between the real and fake versions (Or if there is no fake version) and include a link to a comparison picture if possible.

There isn't yet a page for art in New Horizons on the Fandom wiki, but I'm sure it'll be there soon enough.  For now, this article has some information:
https://animalcrossingworld.com/guides/new-horizons/jolly-redds-art-real-genuine-vs-fake-forgery-cheat-sheet/

**Comment by lexicalunit** [comment]
![acnh-art](https://user-images.githubusercontent.com/1903876/80294688-eb525980-871f-11ea-8958-b7301ad9173e.jpg)

**Comment by theastropath** [comment]
I've pulled all the info from this page on the wiki.  Hopefully the pictures for the sculptures get updated ASAP.

https://animalcrossing.fandom.com/wiki/Forgery_(New_Horizons)

**Comment by theastropath** [comment]
#92 added the basic art information for finding out about forgeries, and #95 added the actual tracking and search functionality to allow for easy trading.
