### ISSUE TITLE
Add info to README about bot permissions

### ISSUE THREAD

**Issue by theastropath** [theastropath/turbot#64]
Need to add info about what permissions the bot needs when being invited to a server (Send Messages, Embed Links, Attach Files are the ones needed for now)

**Comment by theastropath** [comment]
Also probably just outline the general procedure for getting your Discord bot token

**Comment by lexicalunit** [comment]
I used these permissions for the invite link:

![Screen Shot 2020-05-18 at 3 15 11 PM](https://user-images.githubusercontent.com/1903876/82264764-691e1500-991a-11ea-8ac4-307db242e928.png)
